#!/bin/zsh

# Useful Options
setopt interactive_comments
setopt extendedglob
setopt nomatch
setopt menu_complete
setopt auto_list
setopt complete_in_word
setopt autocd
setopt cdable_vars
setopt cd_silent
setopt pushd_silent
unsetopt beep
stty stop undef # Disable ctrl-s to freeze terminal
zle_highlight=('paste:none') # no highlighted paste

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.config/zsh/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
# Needs to stay here or else you'll get a warning
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

setopt NO_HUP # Allow background jobs to continue after exiting shell

# Improve history recording
HISTFILE=$XDG_CACHE_HOME/zsh/history
HISTSIZE=105000
SAVEHIST=100000

setopt EXTENDED_HISTORY          # Write the history file in the ':start:elapsed;command' format.
setopt INC_APPEND_HISTORY        # Write to the history file immediately, not when the shell exits.
setopt SHARE_HISTORY             # Share history between all sessions.
setopt HIST_EXPIRE_DUPS_FIRST    # Expire a duplicate event first when trimming history.
setopt HIST_IGNORE_DUPS          # Do not record an event that was just recorded again.
setopt HIST_IGNORE_ALL_DUPS      # Delete an old recorded event if a new event is a duplicate.
setopt HIST_FIND_NO_DUPS         # Do not display a previously found event.
setopt HIST_IGNORE_SPACE         # Do not record an event starting with a space.
setopt HIST_SAVE_NO_DUPS         # Do not write a duplicate event to the history file.
setopt HIST_VERIFY               # Do not execute immediately upon history expansion.
setopt APPEND_HISTORY            # append to history file
setopt HIST_NO_STORE             # Don't store history commands

# Basic auto/tab complete:
fpath=($ZDOTDIR/zsh_functions $ZDOTDIR/completion $fpath)

# Autoload all functions in zsh_functions
autoload -U ${(M)fpath:#*zsh_functions}/*(.:t)

# Autoload all functions. If fpath changes, then change this respectively
# autoload -U $fpath[1]/*(.:t)

zmodload zsh/complist
autoload -U compinit && compinit
_comp_options+=(globdots) # Include hidden files

# zstyle pattern
# :completion:function:completer:command:argument:tag
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path $XDG_CACHE_HOME/zsh/cache
zstyle ':completion:*' menu select
zstyle ':completion:*:*:*:*:descriptions' format '%F{green}-- %d --%f'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' list-dirs-first true
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}

# Normal files to source
zsh_add_file "zsh-vim-mode"
zsh_add_file "zsh-aliases"
source $ZDOTDIR/plugins/powerlevel10k/powerlevel10k.zsh-theme

# Plugins
# zsh_add_plugin "zdharma/fast-syntax-highlighting"
zsh_add_plugin "Aloxaf/fzf-tab"
zsh_add_plugin "zdharma-continuum/fast-syntax-highlighting"
zsh_add_plugin "romkatv/powerlevel10k"
zsh_add_plugin "zsh-users/zsh-autosuggestions"

# Binds alt+? to the run-help command for word near cursor
unalias run-help
autoload -Uz run-help
# bindkey '\e?' run-help

# FZF
[ -f /usr/share/fzf/completion.zsh ] && source /usr/share/fzf/completion.zsh
[ -f /usr/share/fzf/key-bindings.zsh ] && source /usr/share/fzf/key-bindings.zsh

# FZF-tab
# [[ -f $ZDOTDIR/plugins/fzf-tab/fzf-tab.plugin.zsh ]] && source $ZDOTDIR/plugins/fzf-tab/fzf-tab.plugin.zsh

# To customize prompt, run `p10k configure` or edit ~/.config/zsh/.p10k.zsh.
[[ ! -f ~/.config/zsh/.p10k.zsh ]] || source ~/.config/zsh/.p10k.zsh
