-- local status_ok, autopairs = pcall(require, "nvim-autopairs")
-- if not status_ok then
--   return
-- end
-- autopairs.setup({
--   fast_wrap = {},
-- })
--
-- -- Insert `(` after select function or method item
-- local cmp_autopairs = require('nvim-autopairs.completion.cmp')
-- local cmp = require('cmp')
-- cmp.event:on( 'confirm_done', cmp_autopairs.on_confirm_done())
